name: python-performance-test

on:
  push:
    paths:
      - 'enval'
  workflow_dispatch:
    
jobs:
  python-performance-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/northerntrust-internal/apm0005367-eap-container-images/hardened-ubuntu:latest

    steps:
    - name: Install Python and Pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
    - name: Install pyperformance
      run: python3 -m pip install pyperformance
    - name: Run PyPerformance
      run: pyperformance run --affinity=1 --benchmarks="${{ env.benchmark_list }}"
      
    # Add other actions to build, test, and deploy your project here
    - name: Additional Actions
      run: |
        echo "Add other actions to build, test, and deploy your project."
