name: python-performance-test

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  node-performance-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - name: Install Node.js and NPM
        run: |
          apt-get update
          apt-get install -y nodejs npm

      - name: Install Benchmark.js
        run: npm install benchmark

      - name: Run Node Performance Test
        run: |
          node --version
          npm --version
          node -e "
            const Benchmark = require('benchmark');
            const suite = new Benchmark.Suite;

            // Synchronous test
            suite.add('syncTest', function() {
              for (let i = 0; i < 100000; i++) {
                Math.pow(i, 2);
              }
            });

            // Asynchronous test with simulated delay
            suite.add('asyncTest', {
              defer: true,
              fn: function(deferred) {
                setTimeout(() => {
                  for (let i = 0; i < 100000; i++) {
                    Math.sqrt(i);
                  }
                  deferred.resolve();
                }, 100);
              }
            });

            suite.on('cycle', function(event) {
              console.log(String(event.target));
            });

            suite.on('complete', function() {
              console.log('Fastest is ' + this.filter('fastest').map('name'));
            });

            suite.run({ async: true });
            "



      

